services:
  api:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --reload
    profiles:
      - dev

  api-prod:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}
    profiles:
      - prod

  redis:
    image: redis:7-alpine
    profiles:
      - dev
      - prod

  celery:
    build: .
    command: celery -A worker.celery worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./app:/app
    env_file:
      - .env
    profiles:
      - dev
      - prod
