services:
  api:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --reload
    profiles:
      - dev

  api-prod:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}
    profiles:
      - prod

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: twitter_clone
      POSTGRES_USER: twitter_user
      POSTGRES_PASSWORD: twitter_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - dev
      - prod

  redis:
    image: redis:7-alpine
    profiles:
      - dev
      - prod

  celery:
    build: .
    command: celery -A worker worker --loglevel=info
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app
    env_file:
      - .env
    profiles:
      - dev
      - prod

volumes:
  postgres_data:
